language: rust
cache: cargo
jobs:
  include:
    - stage: build
      script:
        - make
    - stage: test
      before_script:
        - rustup component add rustfmt
      script:
        - make test
