language: rust
jobs:
  include:
    - stage: build
      script:
        - rustup component add rustfmt
        - git clone https://github.com/SchedMD/slurm.git slurm && pushd slurm && ./configure && popd
        - make