[package]
name = "slurm_banking"
version = "0.1.0"
authors = ["Nicolas Chan <nicolas@nicolaschan.com>"]
edition = "2018"

[dependencies]
config = "0.9"
reqwest = "~0.9"
rust_decimal = "1.0.1"
openapi = { path = "../mybrc_rest_client" }

[build-dependencies]
bindgen = "0.49.0"
