[package]
name = "slurm_banking"
version = "0.1.0"
authors = ["Nicolas Chan <nicolas@nicolaschan.com>"]
edition = "2018"

[dependencies]
rust_decimal = "1.0.1"

[build-dependencies]
bindgen = "0.49.0"